swagger: "2.0"
info: Mourad El mehdaoui - TD13 ApiBank 
  title: Transactions API
  version: 1.0.0
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /{userAccountId}/transactions/:
    get:
      tags:
        - Transaction
      summary: customer account 
      description: retrieve customer bank account transactions
      parameters:
        - in: header
          name: Authorization
          description: "\"Bearer [JWT]"
          required: true

        - in: query
          name: userAccountId
          description: user id
          required: true
          schema:
            $ref: '#/definitions/Transactions'
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/TransactionsResponse'
      
        '400':
          description: Bad request
        '401':
           description: Unauthenticated
        '403':
           description: Unauthorized
        '404':
           description: Not found

        '500':
          description: Internal Server Error

  /{accountId}/transactions/{transactionId}/:
    get:
      tags:
        - Transactions 
      summary: Account's singular transaction
      description: API to fetch a particular transaction
      parameters:
        - in: header
          type:  string
          name: Authorization
          description: "\"Bearer [JWT]"
          required: true

        - in: query
          name: userAccountId
          description: user id
          required: true
          schema:
            $ref: '#/definitions/TransactionsId'
        - in: query
          name: transactionId
          description: transaction id
          required: true
          schema:
            $ref: '#/definitions/TransactionsId'
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/TransactionIdResponse'
      
        '400':
          description: Bad request
        '401':
           description: Unauthenticated
        '403':
           description: Unauthorized
        '404':
           description: Not found

        '500':
          description: Internal Server Error

    post:
      tags:
        - Transactions 
      summary: Creates transaction details
      description: Creates a note for the transaction
      parameters:
        - in: header
          type:  string
          name: Authorization
          description: "\"Bearer [JWT]"
          required: true

        - in: body
          name: Body of the request
          description: Adds notes to the transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionsPost'
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/TransactionsOtherResponse'
      
        '400':
          description: Bad request
        '401':
           description: Unauthenticated
        '403':
           description: Unauthorized
        '404':
           description: Not found

        '500':
          description: Internal Server Error
 
    put:
      tags:
        - Transactions 
      summary: Changes transaction details 
      description: Changes the notes or the category of the transaction
      parameters:
        - in: header
          type:  string
          name: Authorization
          description: "\"Bearer [JWT]"
          required: true

        - in: body
          name: Body of the request
          description: Changes the notes and/or the category of the transaction 
          required: true
          schema:
            $ref: '#/definitions/TransactionsPut'
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/TransactionsOtherResponse'
      
        '400':
          description: Bad request
        '401':
           description: Unauthenticated
        '403':
           description: Unauthorized
        '404':
           description: Not found

        '500':
          description: Internal Server Error

definitions:

  # All transactions request payload
  Transactions:
    properties:
      userAccountId:
        type: string
        description: ID of the account
        
  # Transaction details by id
  TransactionId:
      properties:
        userAccountId:
          type: string
          description: ID of the account
        transactionId:
          type: string
          description: ID of the account
        
   # retrieve transactions Api without Notes & Category
  TransactionIdResponse:
    type: array
    items:
      type: object
      properties:
        transactionId:
          type: string
          description: ID of a transaction
        date:
          type: string
          description: Date of the transaction
        description:
          type: string
          description: Description of the transaction
        amount:
          type: number
          description: Amount spent in the transaction
        balance:
          type: number
          description: Account's balance after the transaction
        category:
          type: string
          description: Category of the transaction
        notes:
          type: string
          description: User notes of the transaction
            
  # Message succes delete transacation by transactionid && userAccountId 
  TransactionsMessageSuccess:
      properties:
          message:
            type: string
            description: Message of success
            
            
  TransactionsResponse:
    type: array
    items:
      type: object
      properties:
        transactionId:
          type: string
          description: ID of a transaction
        date:
          type: string
          description: Date of the transaction
        description:
          type: string
          description: Description of the transaction
        amount:
          type: number
          description: Amount spent in the transaction
        balance:
          type: number
          description: Account's balance after the transaction      
          
    # add note or category to transaction
  TransactionsPost:
      properties:
        userAccountId:
          type: string
          description: ID of the account
        transactionId:
          type: string
          description: ID of the transaction
        notes:
          type: string
          description: Notes of the transaction

     
# Transaction Modify
  TransactionsPut:
      properties:
        userAccountId:
          type: string
          description: ID of the account
        transactionId:
          type: string
          description: ID of the transaction
        notes:
          type: string
          description: Notes of the transaction
        category:
          type: string
          description: Category of the transaction

# Response success Crud transaction Notes & category
  TransactionsOtherResponse:
      properties:
          message:
            type: string
            description: Message of success
          
